# NB: this file was automatically generated by Dynare
#     from irbc2.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(15, 15);
gp = zeros(15, 29, 15);
end
return (rp, gp)
end
