# NB: this file was automatically generated by Dynare
#     from irbc2.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(15, 15);
gp = zeros(15, 15, 15);
end
return (rp, gp)
end
