# NB: this file was automatically generated by Dynare
#     from irbc2.mod
#
function steady_state!(ys_::Vector{<: Real}, exo_::Vector{<: Real}, params::Vector{<: Real})
@inbounds begin
    ys_[2]=0;
    ys_[3]=0;
    ys_[5]=0;
    ys_[4]=params[11];
    ys_[1]=log(params[14]);
    ys_[6]=params[14];
    ys_[7]=0;
    ys_[9]=0;
    ys_[10]=0;
    ys_[12]=0;
    ys_[11]=params[11];
    ys_[8]=log(params[14]);
    ys_[13]=params[14];
    ys_[14]=0;
    ys_[15]=1;
    # Auxiliary equations
end
end
